config/routes.rb
Rails.application.routes.draw do
  resources :professional_professions
  resources :service_professional_feedbacks
  resources :professionals
  resources :service_ads
  resources :services
  resources :categories
  get 'message/index'

  devise_for :users, controllers: { sessions: "users/sessions",confirmations: "users/confirmations", registrations: "users/registrations", passwords: "users/passwords"}
  get 'cep/search/:id' =>  'cep#search'

  resources :professions

  devise_scope :user do
    get "/users/cancel" => "users/registrations"
  end

  root 'welcome#index'

  get 'servicesByCategory/retrieveByCategory' => "services#retrieveByCategory", :as => 'remote_select' 

end

app/models/address.rb
class Address < ActiveRecord::Base
	validates_presence_of :main,:cep,:city,:district,:num,:state
	belongs_to :user

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :state
  has_many :city_coverages
end

app/models/city_coverage.rb
class CityCoverage < ActiveRecord::Base
  belongs_to :service_ad , :inverse_of => :city_coverages
  belongs_to :city , :inverse_of => :city_coverages
end

app/models/district.rb
class District < ActiveRecord::Base
  belongs_to :city
  has_and_belongs_to_many :service_ads
end

app/models/district_coverage.rb
class DistrictCoverage < ActiveRecord::Base
  belongs_to :service_ad
  belongs_to :district
end

app/models/phone.rb
class Phone < ActiveRecord::Base
	belongs_to :user
end

app/models/profession.rb
class Profession < ActiveRecord::Base
	validates_presence_of :name,:description
end

app/models/professional.rb
class Professional < ActiveRecord::Base
end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :category
end

app/models/service_ad.rb
class ServiceAd < ActiveRecord::Base
  belongs_to :service
  has_one :service_unit
  has_one :state
  has_one :category

  has_many :service_images, :dependent => :destroy
  has_many :city_coverages, :dependent => :destroy, inverse_of: :service_ad
  has_many :cities, through: :city_coverages
  has_many :district_coverages, :dependent => :destroy, inverse_of: :service_ad
  has_many :districts, through: :district_coverages

  accepts_nested_attributes_for :service_images
  accepts_nested_attributes_for :city_coverages
  accepts_nested_attributes_for :district_coverages



  validates_presence_of :service,:title,:description,:price,:user_id,:service_id,:service_unit_id,:state_id,:category_id

end

app/models/service_image.rb
class ServiceImage < ActiveRecord::Base
  belongs_to :service_ad

  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment :photo, presence: true,
                       content_type: { content_type: "image/jpeg" },
                       size: { in: 0..10.megabytes }
end

app/models/service_unit.rb
class ServiceUnit < ActiveRecord::Base
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :addresses, :dependent => :destroy

  accepts_nested_attributes_for :addresses

  validates_presence_of :cpf,:phone_number,:first_name,:last_name,:gender,:addresses

  attr_accessor :term

end

app/controllers/cep_controller.rb
class CepController < ApplicationController



  def findCepSite cep
    HTTParty.post('http://www.buscacep.correios.com.br/servicos/dnec/consultaLogradouroAction.do',:query=>{:CEP =>cep,:Metodo =>'listaLogradouro',:TipoConsulta =>'cep' })
  end


  def search
  	@address = Address.new
  	result = findCepSite params[:id]
  	page = Nokogiri::HTML(result.force_encoding("windows-1252"))
    select =  page.css('table tr td').select{|td| td['style'] == "padding: 2px"}
    if !select.empty?
    @address.main =  select[0].text
    @address.district =  select[1].text
    @address.city =  select[2].text
    @address.state = select[3].text
    @address.cep  = select[4].text
    end
    respond_to do |format|
  		format.json { render json: @address }
	  end
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  def index
    @services = Service.all
  end

  # GET /services/1
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

    # GET /services/1/edit
  def retrieveByCategory
    @services = Service.where(:category_id => params[:send_id]).to_a
    render json: @services
  end

  # POST /services
  def create
    @service = Service.new(service_params)
    if @service.save
      redirect_to @service, notice: t('helpers.messages.save' , model:t('activerecord.models.service.one'))
    else
      render :new
    end
  end

  # PATCH/PUT /services/1
  def update
    if @service.update(service_params)
      redirect_to @service, notice: t('helpers.messages.update' , model:t('activerecord.models.service.one'))
    else
      render :edit
    end
  end

  # DELETE /services/1
  def destroy
    @service.destroy
    redirect_to services_url, notice: t('helpers.messages.delete' , model:t('activerecord.models.service.one'))
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def service_params
      params.require(:service).permit(:name, :description, :active, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def my_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <h5><strong>#{sentence}</strong></h5>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cep_helper.rb
module CepHelper
end

app/helpers/message_helper.rb
module MessageHelper
  def bootstrap_flash_message(options = {})
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?

      Array(message).each do |msg|
        flash_messages << msg
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.text_field :category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Services</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Active</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.name %></td>
        <td><%= service.description %></td>
        <td><%= service.active %></td>
        <td><%= service.category %></td>
        <td><%= link_to 'Show', service %></td>
        <td><%= link_to 'Edit', edit_service_path(service) %></td>
        <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_service_path %>

app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form' %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @service.description %>
</p>

<p>
  <strong>Active:</strong>
  <%= @service.active %>
</p>

<p>
  <strong>Category:</strong>
  <%= @service.category %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>