config/routes.rb
Rails.application.routes.draw do
  resources :professional_professions
  resources :service_professional_feedbacks
  resources :professionals
  resources :service_ads
  resources :services
  resources :categories
  get 'message/index'

  devise_for :users, controllers: { sessions: "users/sessions",confirmations: "users/confirmations", registrations: "users/registrations", passwords: "users/passwords"}
  get 'cep/search/:id' =>  'cep#search'

  resources :professions

  devise_scope :user do
    get "/users/cancel" => "users/registrations"
  end

  root 'welcome#index'

  get 'servicesByCategory/retrieveByCategory' => "services#retrieveByCategory", :as => 'remote_select' 

end

app/models/address.rb
class Address < ActiveRecord::Base
	validates_presence_of :main,:cep,:city,:district,:num,:state
	belongs_to :user

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :state
  has_many :city_coverages
end

app/models/city_coverage.rb
class CityCoverage < ActiveRecord::Base
  belongs_to :service_ad , :inverse_of => :city_coverages
  belongs_to :city , :inverse_of => :city_coverages
end

app/models/district.rb
class District < ActiveRecord::Base
  belongs_to :city
  has_and_belongs_to_many :service_ads
end

app/models/district_coverage.rb
class DistrictCoverage < ActiveRecord::Base
  belongs_to :service_ad
  belongs_to :district
end

app/models/phone.rb
class Phone < ActiveRecord::Base
	belongs_to :user
end

app/models/profession.rb
class Profession < ActiveRecord::Base
	validates_presence_of :name,:description
end

app/models/professional.rb
class Professional < ActiveRecord::Base
end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :category
end

app/models/service_ad.rb
class ServiceAd < ActiveRecord::Base
  belongs_to :service
  has_one :service_unit
  has_one :state
  has_one :category

  has_many :service_images, :dependent => :destroy
  has_many :city_coverages, :dependent => :destroy, inverse_of: :service_ad
  has_many :cities, through: :city_coverages
  has_many :district_coverages, :dependent => :destroy, inverse_of: :service_ad
  has_many :districts, through: :district_coverages

  accepts_nested_attributes_for :service_images
  accepts_nested_attributes_for :city_coverages
  accepts_nested_attributes_for :district_coverages



  validates_presence_of :service,:title,:description,:price,:user_id,:service_id,:service_unit_id,:state_id,:category_id

end

app/models/service_image.rb
class ServiceImage < ActiveRecord::Base
  belongs_to :service_ad

  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment :photo, presence: true,
                       content_type: { content_type: "image/jpeg" },
                       size: { in: 0..10.megabytes }
end

app/models/service_professional_feedback.rb
class ServiceProfessionalFeedback < ActiveRecord::Base
end

app/models/service_unit.rb
class ServiceUnit < ActiveRecord::Base
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :addresses, :dependent => :destroy

  accepts_nested_attributes_for :addresses

  validates_presence_of :cpf,:phone_number,:first_name,:last_name,:gender,:addresses

  attr_accessor :term

end

app/controllers/service_professional_feedbacks_controller.rb
class ServiceProfessionalFeedbacksController < ApplicationController
  before_action :set_service_professional_feedback, only: [:show, :edit, :update, :destroy]

  # GET /service_professional_feedbacks
  def index
    @service_professional_feedbacks = ServiceProfessionalFeedback.all
  end

  # GET /service_professional_feedbacks/1
  def show
  end

  # GET /service_professional_feedbacks/new
  def new
    @service_professional_feedback = ServiceProfessionalFeedback.new
  end

  # GET /service_professional_feedbacks/1/edit
  def edit
  end

  # POST /service_professional_feedbacks
  def create
    @service_professional_feedback = ServiceProfessionalFeedback.new(service_professional_feedback_params)

    if @service_professional_feedback.save
      redirect_to @service_professional_feedback, notice: t('helpers.messages.save' , model:t('activerecord.models.service_professional_feedback.one'))
    else
      render :new
    end
  end

  # PATCH/PUT /service_professional_feedbacks/1
  def update
    if @service_professional_feedback.update(service_professional_feedback_params)
      redirect_to @service_professional_feedback, notice: t('helpers.messages.update' , model:t('activerecord.models.service_professional_feedback.one'))
    else
      render :edit
    end
  end

  # DELETE /service_professional_feedbacks/1
  def destroy
    @service_professional_feedback.destroy
    redirect_to service_professional_feedbacks_url, notice: t('helpers.messages.delete' , model:t('activerecord.models.service_professional_feedback.one'))
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_professional_feedback
      @service_professional_feedback = ServiceProfessionalFeedback.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def service_professional_feedback_params

      params.require(:service_professional_feedback).permit(:professional_service_id, :quantity_stars, :user_id, :feedback)

    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cep_helper.rb
module CepHelper
end

app/helpers/message_helper.rb
module MessageHelper
  def bootstrap_flash_message(options = {})
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?

      Array(message).each do |msg|
        flash_messages << msg
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/service_professional_feedbacks_helper.rb
module ServiceProfessionalFeedbacksHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/service_professional_feedbacks/_form.html.erb
<%= form_for(@service_professional_feedback) do |f| %>
  <% if @service_professional_feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service_professional_feedback.errors.count, "error") %> prohibited this service_professional_feedback from being saved:</h2>

      <ul>
      <% @service_professional_feedback.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :professional_service_id %><br>
    <%= f.number_field :professional_service_id %>
  </div>
  <div class="field">
    <%= f.label :quantity_stars %><br>
    <%= f.number_field :quantity_stars %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :feedback %><br>
    <%= f.text_field :feedback %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/service_professional_feedbacks/edit.html.erb
<h1>Editing Service Professional Feedback</h1>

<%= render 'form' %>

<%= link_to 'Show', @service_professional_feedback %> |
<%= link_to 'Back', service_professional_feedbacks_path %>

app/views/service_professional_feedbacks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Service Professional Feedbacks</h1>

<table>
  <thead>
    <tr>
      <th>Professional service</th>
      <th>Quantity stars</th>
      <th>User</th>
      <th>Feedback</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @service_professional_feedbacks.each do |service_professional_feedback| %>
      <tr>
        <td><%= service_professional_feedback.professional_service_id %></td>
        <td><%= service_professional_feedback.quantity_stars %></td>
        <td><%= service_professional_feedback.user_id %></td>
        <td><%= service_professional_feedback.feedback %></td>
        <td><%= link_to 'Show', service_professional_feedback %></td>
        <td><%= link_to 'Edit', edit_service_professional_feedback_path(service_professional_feedback) %></td>
        <td><%= link_to 'Destroy', service_professional_feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service professional feedback', new_service_professional_feedback_path %>

app/views/service_professional_feedbacks/new.html.erb
<h1>New Service Professional Feedback</h1>

<%= render 'form' %>

<%= link_to 'Back', service_professional_feedbacks_path %>

app/views/service_professional_feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Professional service:</strong>
  <%= @service_professional_feedback.professional_service_id %>
</p>

<p>
  <strong>Quantity stars:</strong>
  <%= @service_professional_feedback.quantity_stars %>
</p>

<p>
  <strong>User:</strong>
  <%= @service_professional_feedback.user_id %>
</p>

<p>
  <strong>Feedback:</strong>
  <%= @service_professional_feedback.feedback %>
</p>

<%= link_to 'Edit', edit_service_professional_feedback_path(@service_professional_feedback) %> |
<%= link_to 'Back', service_professional_feedbacks_path %>