config/routes.rb
Rails.application.routes.draw do
  resources :professional_professions
  resources :service_professional_feedbacks
  resources :professionals
  resources :service_ads
  resources :services
  resources :categories
  get 'message/index'

  devise_for :users, controllers: { sessions: "users/sessions",confirmations: "users/confirmations", registrations: "users/registrations", passwords: "users/passwords"}
  get 'cep/search/:id' =>  'cep#search'

  resources :professions

  devise_scope :user do
    get "/users/cancel" => "users/registrations"
  end

  root 'welcome#index'

  get 'servicesByCategory/retrieveByCategory' => "services#retrieveByCategory", :as => 'remote_select' 

end

app/models/address.rb
class Address < ActiveRecord::Base
	validates_presence_of :main,:cep,:city,:district,:num,:state
	belongs_to :user

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :state
  has_many :city_coverages
end

app/models/city_coverage.rb
class CityCoverage < ActiveRecord::Base
  belongs_to :service_ad , :inverse_of => :city_coverages
  belongs_to :city , :inverse_of => :city_coverages
end

app/models/district.rb
class District < ActiveRecord::Base
  belongs_to :city
  has_and_belongs_to_many :service_ads
end

app/models/district_coverage.rb
class DistrictCoverage < ActiveRecord::Base
  belongs_to :service_ad
  belongs_to :district
end

app/models/phone.rb
class Phone < ActiveRecord::Base
	belongs_to :user
end

app/models/profession.rb
class Profession < ActiveRecord::Base
	validates_presence_of :name,:description
end

app/models/professional.rb
class Professional < ActiveRecord::Base
end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :category
end

app/models/service_ad.rb
class ServiceAd < ActiveRecord::Base
  belongs_to :service
  has_one :service_unit
  has_one :state
  has_one :category

  has_many :service_images, :dependent => :destroy
  has_many :city_coverages, :dependent => :destroy, inverse_of: :service_ad
  has_many :cities, through: :city_coverages
  has_many :district_coverages, :dependent => :destroy, inverse_of: :service_ad
  has_many :districts, through: :district_coverages

  accepts_nested_attributes_for :service_images
  accepts_nested_attributes_for :city_coverages
  accepts_nested_attributes_for :district_coverages



  validates_presence_of :service,:title,:description,:price,:user_id,:service_id,:service_unit_id,:state_id,:category_id

end

app/models/service_image.rb
class ServiceImage < ActiveRecord::Base
  belongs_to :service_ad

  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment :photo, presence: true,
                       content_type: { content_type: "image/jpeg" },
                       size: { in: 0..10.megabytes }
end

app/models/service_unit.rb
class ServiceUnit < ActiveRecord::Base
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :addresses, :dependent => :destroy

  accepts_nested_attributes_for :addresses

  validates_presence_of :cpf,:phone_number,:first_name,:last_name,:gender,:addresses

  attr_accessor :term

end

app/controllers/cep_controller.rb
class CepController < ApplicationController



  def findCepSite cep
    HTTParty.post('http://www.buscacep.correios.com.br/servicos/dnec/consultaLogradouroAction.do',:query=>{:CEP =>cep,:Metodo =>'listaLogradouro',:TipoConsulta =>'cep' })
  end


  def search
  	@address = Address.new
  	result = findCepSite params[:id]
  	page = Nokogiri::HTML(result.force_encoding("windows-1252"))
    select =  page.css('table tr td').select{|td| td['style'] == "padding: 2px"}
    if !select.empty?
    @address.main =  select[0].text
    @address.district =  select[1].text
    @address.city =  select[2].text
    @address.state = select[3].text
    @address.cep  = select[4].text
    end
    respond_to do |format|
  		format.json { render json: @address }
	  end
  end
end

app/controllers/service_ads_controller.rb
class ServiceAdsController < ApplicationController
  before_action :set_service_ad, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]

  # GET /service_ads
  def index
    my_hash = {}
    my_join_hash = {}
    if params.key?(:service)
      my_hash['service_id'] = params[:service]
    end
    if params.key?(:category)
      my_hash['category_id'] = params[:category]
    end
    if params.key?(:district)
      my_join_hash['districts'] = {id: params[:district]}
    end
    if my_hash.empty?
      @service_ads = ServiceAd.all
    elsif my_join_hash.empty?
      @service = params[:service]
      @category = params[:category]
      @service_ads = ServiceAd.where(my_hash).find_each
    else
      @service = params[:service]
      @category = params[:category]
      @district = params[:district]
      @service_ads = ServiceAd.where(my_hash).joins(:districts).where(my_join_hash).find_each
    end

  end

  # GET /service_ads/1
  def show
  end

  # GET /service_ads/new
  def new
    user_param = ActionController::Parameters.new(user_id: current_user.attributes['id'], active: true)
    user_param.permit!
    @service_ad = ServiceAd.new(user_param)
    @city_coverages = @service_ad.city_coverages.build
    @district_coverages = @service_ad.district_coverages.build
    @serviceList = Array.new
    5.times do
      @service_ad.service_images.build
    end
  end

  # GET /service_ads/1/edit
  def edit
  end

  # POST /service_ads
  def create
    service_ad_params[:price].gsub!(/,/, '.')
    @service_ad = ServiceAd.new(service_ad_params)
    if @service_ad.save
      redirect_to "/message/index", notice: t('helpers.messages.save', model: t('activerecord.models.service_ad.one'))
    else
      @serviceList = Service.where(:category_id => @service_ad.category_id).to_a
      5.times do
        @service_ad.service_images.build
      end
      render :new
    end
  end

  # PATCH/PUT /service_ads/1
  def update
    if @service_ad.update(service_ad_params)
      redirect_to @service_ad, notice: t('helpers.messages.update', model: t('activerecord.models.service_ad.one'))
    else
      @serviceList = Service.where(:category_id => @service_ad.category).to_a
      5.times do
        @service_ad.service_images.build
      end
      render :edit
    end
  end

  # DELETE /service_ads/1
  def destroy
    @service_ad.destroy
    redirect_to service_ads_url, notice: t('helpers.messages.delete', model: t('activerecord.models.service_ad.one'))
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_service_ad
    @service_ad = ServiceAd.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def service_ad_params
    params.require(:service_ad).permit!
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cep_helper.rb
module CepHelper
end

app/helpers/message_helper.rb
module MessageHelper
  def bootstrap_flash_message(options = {})
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?

      Array(message).each do |msg|
        flash_messages << msg
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/service_ads_helper.rb
module ServiceAdsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/service_ads/_form.html.erb
<%= bootstrap_form_for(@service_ad, layout: :horizontal, inline_errors: false, html: {multipart: true}) do |f| %>
    <fieldset>
      <%= f.hidden_field :user_id %>
      <%= f.hidden_field :active %>
      <script>
        $(document).ready(function() {
          $('#service_ad_category_id').change(function() {
            $.ajax({
              url: "<%= remote_select_url %>", // this will be routed
              type: 'GET',
              data: {
                send_id: $("#service_ad_category_id").val()
              },
              async: true,
              dataType: "json",
              error: function(XMLHttpRequest, errorTextStatus, error){
                alert("Failed: "+ errorTextStatus+" ;"+error);
              },
              success: function(data){
                if(data == null){
                  $("#service_ad_service_id").empty().append(new Option('Selecione', ''));
                }else if(data.length){
                  // here we iterate the json result
                  for(var i in data)
                  {
                    var id = data[i].id;
                    var title = data[i].name;
                    $("#service_ad_service_id").append(new Option(title, id));
                  }
                }else{
                  var id = data.id;
                  var title = data.name;
                  $("#service_ad_service_id").append(new Option(title, id));
                }

              }
            });
          });

        });
      </script>
      <!-- Select Basic -->
      <%= f.collection_select :category_id, Category.all, :id, :name, {include_blank: 'Selecione', control_col: "col-md-8", label_col: "col-md-3" } %>

      <%= f.select :service_id, @serviceList.collect {|p| [ p.name, p.id ] }, {include_blank: 'Selecione', control_col: "col-md-8", label_col: "col-md-3" } %>


      <!-- Text input-->
      <%= f.text_field :title, control_col: "col-md-8", label_col: "col-md-3", help: t('.helpTitle') %>
      <!-- Textarea -->
      <%= f.text_area :description, control_col: "col-md-8", label_col: "col-md-3" ,rows:7, help: t('.helpDescription') %>
      <%= f.text_field :price, prepend: "R$", data: { inputmask: "'alias':'currency', 'radixPoint': ',', 'groupSeparator': '.', 'prefix':'', 'max':100000, 'removeMaskOnSubmit':true "}, control_col: "col-md-4", label_col: "col-md-3" %>

      <%= f.collection_select :service_unit_id, ServiceUnit.all, :id, :name, {include_blank: 'Selecione', control_col: "col-md-4", label_col: "col-md-3" } %>

      <!-- photo -->
      <div class="form-group">
        <label class="col-md-3 control-label" for="textarea"> <%= f.label :picture%> </label>
        <div class="col-md-8">
          <%= f.fields_for :service_images do |image| %>
              <div class="mb10">
                <%= image.file_field_without_bootstrap :photo , class: 'file fileuploadservice', data:{'preview-file-type':'text'} %>
              </div>
          <% end %>
          <p class="help-block"><%= t '.realphotos'%></p>
        </div>
      </div>
      <div class="content-subheading">
        <i class="icon-location fa"></i>
        <strong><%= t 'service_ads.new.comprehensiveness' %></strong>
      </div>
      <%= f.collection_select :state_id, State.where({active: true}), :id, :name, {control_col: "col-md-6", label_col: "col-md-4"} %>
      <%= f.collection_select :city_ids, City.where({active: true}), :id, :name, {control_col: "col-md-6", label_col: "col-md-4"} %>


        <%=f.collection_check_boxes(:district_ids,District.all, :id, :name, {control_col: "col-md-6", label_col: "col-md-4"})%>
      <!-- Button  -->
      <div class="form-group">
        <label class="col-md-3 control-label"></label>
        <div class="col-md-8">
          <%= f.submit 'Submit', class:"btn btn-success btn-lg" %>
        </div>
      </div>
    </fieldset>
  <% end %>

app/views/service_ads/edit.html.erb
<h1>Editing Service Ad</h1>

<%= render 'form' %>

<%= link_to 'Show', @service_ad %> |
<%= link_to 'Back', service_ads_path %>

app/views/service_ads/new.html.erb
<div class="main-container">
  <div class="container">
    <div class="row">
      <%= bootstrap_flash %>
      <div class="col-md-9 page-content">
        <div class="inner-box category-content">
          <h2 class="title-2 uppercase"><strong> <i class="icon-docs"></i> <%= t('.title')%></strong></h2>
          <div class="row">
            <div class="col-sm-12">
              <%= render 'form' %>
            </div>
          </div>
        </div>
      </div>
      <!-- /.page-content -->

      <div class="col-md-3 reg-sidebar">
        <div class="reg-sidebar-inner text-center">
          <div class="promo-text-box"><i class=" icon-picture fa fa-4x icon-color-1"></i>
            <h3><strong><%= t '.free_classified_ad'%></strong></h3>
            <p> Preencha os dados ao lado para publicar seu anuncio inteiramente grátis. Utilize as opções disponiveis pra melhor destacar seu anuncio </p>
          </div>

          <div class="panel sidebar-panel">
            <div class="panel-heading uppercase">
              <small><strong><%= t '.howtosell'%></strong></small>
            </div>
            <div class="panel-content">
              <div class="panel-body text-left">
                <ul class="list-check">
                  <li> <%= t '.howtosell_item1'%></li>
                  <li> <%= t '.howtosell_item2'%></li>
                  <li> <%= t '.howtosell_item3'%></li>
                  <li> <%= t '.howtosell_item4'%> </li>
                  <li> <%= t '.howtosell_item5'%> </li>

                </ul>
              </div>
            </div>
          </div>


        </div>
      </div><!--/.reg-sidebar-->
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->
</div>
<script src="/js/fileinput.min.js" type="text/javascript"></script> 
<script>
// initialize with defaults
$(".fileuploadservice").fileinput({'showUpload':false, 'previewFileType':'any', browseLabel:'Procurar...',removeLabel:'Remover'});
</script>
<!-- /.main-container -->

app/views/service_ads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @service_ad.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @service_ad.description %>
</p>

<p>
  <strong>Active:</strong>
  <%= @service_ad.active %>
</p>

<p>
  <strong>Price:</strong>
  <%= @service_ad.price %>
</p>

<p>
  <strong>Service:</strong>
  <%= @service_ad.service %>
</p>

<p>
  <strong>User:</strong>
  <%= @service_ad.user_id %>
</p>

<%= link_to 'Edit', edit_service_ad_path(@service_ad) %> |
<%= link_to 'Back', service_ads_path %>